#!/usr/bin/env bash
set -euo pipefail

ROOT="${1:-$(pwd)}"
ROOT="$(cd "$ROOT" && pwd)"
cd "$ROOT"

for need in VERSION dashboard/dashboard.html dashboard/dashboard.js dashboard/sensor_history_multi.h firmware/esp32-c3-multi-sensor.yaml; do
  [[ -f "$need" ]] || { echo "Missing required file: $need" >&2; exit 1; }
done

mkdir -p scripts

cat > scripts/deploy-to-esphome.sh <<'SH'
#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

VERSION_REF="${1:-main}"

if [[ "$VERSION_REF" != "main" ]]; then
  git fetch --all --tags
  if git rev-parse "$VERSION_REF" >/dev/null 2>&1; then
    git checkout "$VERSION_REF"
  else
    echo "Git ref not found: $VERSION_REF" >&2
    exit 1
  fi
else
  git checkout main
  git pull --ff-only
fi

./scripts/preflight.sh
esphome compile firmware/esp32-c3-multi-sensor.yaml
SH
chmod +x scripts/deploy-to-esphome.sh

cat > scripts/generate-header.sh <<'SH'
#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

INPUT="${1:-dashboard/dashboard.html}"
OUTPUT="${2:-dashboard/dashboard.h}"

cat > "$OUTPUT" <<'EOF2'
#pragma once
// dashboard.h - embedded dashboard payload
// Auto-generated from dashboard/dashboard.html by scripts/generate-header.sh
// Do not edit this file directly - edit dashboard/dashboard.html instead.

#if defined(PROGMEM)
#define DASHBOARD_STORAGE_ATTR PROGMEM
#else
#define DASHBOARD_STORAGE_ATTR
#endif

static const char DASHBOARD_HTML[] DASHBOARD_STORAGE_ATTR = R"DASH64(
EOF2
cat "$INPUT" >> "$OUTPUT"
cat >> "$OUTPUT" <<'EOF2'
)DASH64";
EOF2

echo "Generated $OUTPUT from $INPUT"
SH
chmod +x scripts/generate-header.sh

cat > scripts/preflight.sh <<'SH'
#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

VER_RAW="$(tr -d '[:space:]' < VERSION)"
VER_TAG="${VER_RAW#v}"
VER_TAG="v${VER_TAG}"

FILES=(
  "VERSION"
  "dashboard/dashboard.html"
  "dashboard/dashboard.js"
  "dashboard/dashboard.h"
  "dashboard/sensor_history_multi.h"
  "firmware/esp32-c3-multi-sensor.yaml"
  "partitions/esp32-c3-multi-partitions.csv"
  "scripts/generate-header.sh"
  "scripts/deploy-to-esphome.sh"
)

for f in "${FILES[@]}"; do
  [[ -f "$f" ]] || { echo "Missing $f"; exit 1; }
done

check_contains() {
  local label="$1" file="$2" needle="$3"
  if grep -Fq -- "$needle" "$file"; then
    echo "$label: PASS"
  else
    echo "$label: FAIL"
    exit 1
  fi
}

check_not_contains() {
  local label="$1" file="$2" needle="$3"
  if grep -Fq -- "$needle" "$file"; then
    echo "$label: FAIL"
    exit 1
  else
    echo "$label: PASS"
  fi
}

check_contains "yaml_includes_dashboard" firmware/esp32-c3-multi-sensor.yaml "- ../dashboard/dashboard.h"
check_contains "yaml_includes_history" firmware/esp32-c3-multi-sensor.yaml "- ../dashboard/sensor_history_multi.h"
check_contains "yaml_uses_canonical_partitions" firmware/esp32-c3-multi-sensor.yaml "partitions: ../partitions/esp32-c3-multi-partitions.csv"
check_contains "generator_targets_dashboard_html" scripts/generate-header.sh "dashboard/dashboard.html"
check_contains "generator_targets_dashboard_h" scripts/generate-header.sh "dashboard/dashboard.h"
check_contains "header_generated_from_canonical_html" dashboard/dashboard.h "Auto-generated from dashboard/dashboard.html"
check_contains "deploy_targets_canonical_yaml" scripts/deploy-to-esphome.sh "firmware/esp32-c3-multi-sensor.yaml"
check_contains "js_version_matches_VERSION" dashboard/dashboard.js "App.version = '${VER_TAG}'"
check_contains "export_all_is_sequential" dashboard/dashboard.js "fetchAllSensorHistoryRowsSequentially"
check_contains "theme_redraw_present" dashboard/dashboard.js "refreshChartsAfterVisualChange"
check_contains "bind_events_present" dashboard/dashboard.js "function bindEvents()"
check_contains "state_write_chokepoints_present" dashboard/dashboard.js "App.State.setSensors("
check_contains "recolor_updates_point_markers" dashboard/dashboard.js "pointBackgroundColor"
check_not_contains "yaml_no_old_versioned_header_name" firmware/esp32-c3-multi-sensor.yaml "dashboard-v7.3.4.2.h"
check_not_contains "yaml_no_old_versioned_history_name" firmware/esp32-c3-multi-sensor.yaml "sensor_history_multi-v7.3.4.2.h"
check_not_contains "yaml_no_old_versioned_partition_name" firmware/esp32-c3-multi-sensor.yaml "esp32-c3-multi-v7.3.4.2-partitions.csv"

node --check dashboard/dashboard.js
echo "node_check: PASS"

node <<'NODE'
const fs = require('fs');
const vm = require('vm');
const code = fs.readFileSync('dashboard/dashboard.js', 'utf8');
function dummyEl() {
  return {
    classList: { add(){}, remove(){}, toggle(){}, contains(){ return false; } },
    textContent: '', innerHTML: '', value: '', style: {}, dataset: {},
    appendChild(){}, removeChild(){}, setAttribute(){}, removeAttribute(){},
    addEventListener(){}, removeEventListener(){}, focus(){}, select(){}, click(){},
    getContext(){ return {}; }
  };
}
const document = {
  documentElement: { classList: { add(){}, remove(){}, contains(){ return false; }, toggle(){} } },
  body: dummyEl(),
  getElementById(){ return dummyEl(); },
  createElement(){ return dummyEl(); },
  addEventListener(){},
  removeEventListener(){}
};
const context = {
  console,
  window: {
    App: {},
    location: { protocol: 'http:', hostname: 'localhost', href: 'http://localhost/', origin: 'http://localhost' },
    setTimeout: () => 0,
    clearTimeout: () => {},
    setInterval: () => 0,
    clearInterval: () => {}
  },
  document,
  localStorage: { getItem(){ return null; }, setItem(){} },
  setTimeout: () => 0,
  clearTimeout: () => {},
  setInterval: () => 0,
  clearInterval: () => {},
  URL,
  fetch: () => Promise.reject(new Error('fetch not available in runtime smoke')),
  EventSource: function(){},
  Chart: function(){}
};
context.window.document = document;
context.window.localStorage = context.localStorage;
context.window.fetch = context.fetch;
context.window.EventSource = context.EventSource;
context.window.Chart = context.Chart;
vm.createContext(context);
try {
  vm.runInContext(code, context, { filename: 'dashboard.js' });
  console.log('runtime_smoke: PASS');
} catch (err) {
  console.error('runtime_smoke: FAIL');
  console.error(err && err.stack ? err.stack : err);
  process.exit(1);
}
NODE

echo "preflight: PASS"
SH
chmod +x scripts/preflight.sh

python3 <<'PY'
from pathlib import Path

p = Path('firmware/esp32-c3-multi-sensor.yaml')
text = p.read_text(encoding='utf-8')
replacements = {
    'dashboard-v7.3.4.2.h': '../dashboard/dashboard.h',
    'sensor_history_multi-v7.3.4.2.h': '../dashboard/sensor_history_multi.h',
    'esp32-c3-multi-v7.3.4.2-partitions.csv': '../partitions/esp32-c3-multi-partitions.csv',
    'esp32-c3-multi-sensor-v7.3.4.2.yaml': 'firmware/esp32-c3-multi-sensor.yaml',
    'dashboard-v7.3.4.2.html': 'dashboard/dashboard.html',
    'dashboard-v7.3.4.2.js': 'dashboard/dashboard.js',
    'dashboard-v7.3.4.2.h': '../dashboard/dashboard.h',
    'sensor_history_multi-v7.3.4.2.h': '../dashboard/sensor_history_multi.h',
    'esp32-c3-multi-v7.3.4.2-partitions.csv': '../partitions/esp32-c3-multi-partitions.csv',
    'generate-header-v7.3.4.2.sh': 'scripts/generate-header.sh',
    'secrets-example-v7.3.4.2.yaml': 'secrets/secrets-example.yaml',
}
for old, new in replacements.items():
    text = text.replace(old, new)
p.write_text(text, encoding='utf-8')
PY

mkdir -p partitions
if [[ -f partitions/esp32-c3-multi-v7.3.4.2-partitions.csv && ! -f partitions/esp32-c3-multi-partitions.csv ]]; then
  cp partitions/esp32-c3-multi-v7.3.4.2-partitions.csv partitions/esp32-c3-multi-partitions.csv
fi

mkdir -p secrets
if [[ ! -f secrets/secrets-example.yaml ]]; then
  cat > secrets/secrets-example.yaml <<'EOF2'
# Copy to secrets.yaml locally and fill in real values.
wifi_ssid: "YOUR_WIFI_SSID"
wifi_password: "YOUR_WIFI_PASSWORD"
gateway_mgmt_username: "admin"
gateway_mgmt_password: "change-me"
EOF2
fi

./scripts/generate-header.sh

echo
echo "Normalization complete. Recommended next steps:"
echo "  git status"
echo "  ./scripts/preflight.sh"
echo "  esphome compile firmware/esp32-c3-multi-sensor.yaml"
