#pragma once
// gateway_manifest.h — generated v2 manifest JSON
// Auto-generated by scripts/render_sensor_config.py — do not edit

static const char GATEWAY_MANIFEST_JSON[] = R"MANIFEST(
{
  "ok": true,
  "schema_version": 2,
  "source": "active-manifest",
  "version": "v7.5.1",
  "sensor_count": 3,
  "gateway": {
    "id": "gw-main",
    "name": "Main Gateway",
    "role": "satellite",
    "hardware": "ESP32-C3"
  },
  "history": {
    "backend": "nvs",
    "retention_hours": 1080,
    "ram_window_hours": 24,
    "sample_interval_seconds": 900
  },
  "metrics": [
    {
      "key": "temp",
      "name": "Temperature",
      "class": "analog_numeric",
      "data_type": "float",
      "unit": "celsius",
      "unit_symbol": "°C",
      "bounds": {
        "min": -50,
        "max": 80
      },
      "history": true,
      "history_suffix": "temp",
      "display": {
        "precision": 1,
        "chart": true
      }
    },
    {
      "key": "hum",
      "name": "Humidity",
      "class": "analog_numeric",
      "data_type": "float",
      "unit": "percent",
      "unit_symbol": "%",
      "bounds": {
        "min": 0,
        "max": 100
      },
      "history": true,
      "history_suffix": "hum",
      "display": {
        "precision": 1,
        "chart": true
      }
    }
  ],
  "sensors": [
    {
      "id": "office",
      "name": "Office",
      "metrics": [
        {
          "key": "temp",
          "history": "/history/office/temp"
        },
        {
          "key": "hum",
          "history": "/history/office/hum"
        }
      ]
    },
    {
      "id": "first_floor",
      "name": "First Floor",
      "metrics": [
        {
          "key": "temp",
          "history": "/history/first_floor/temp"
        },
        {
          "key": "hum",
          "history": "/history/first_floor/hum"
        }
      ]
    },
    {
      "id": "outside",
      "name": "Outside",
      "metrics": [
        {
          "key": "temp",
          "history": "/history/outside/temp"
        },
        {
          "key": "hum",
          "history": "/history/outside/hum"
        }
      ]
    }
  ]
}
)MANIFEST";
