#pragma once
// gateway_manifest.h — generated v2 manifest JSON
// Auto-generated by scripts/render_sensor_config.py v7.5.1 — do not edit

static const char GATEWAY_MANIFEST_JSON[] = R"MANIFEST(
{
  "ok": true,
  "schema_version": 2,
  "source": "firmware",
  "version": "v7.5.1",
  "gateway": {
    "id": "gw-main",
    "name": "Main Gateway",
    "role": "satellite",
    "hardware": "ESP32-C3"
  },
  "history": {
    "backend": "nvs",
    "retention_hours": 1080,
    "ram_window_hours": 24,
    "sample_interval_seconds": 900
  },
  "sensor_count": 3,
  "sensors": [
    {
      "id": "office",
      "name": "Office",
      "category": "environmental",
      "adapter": "thermopro_ble",
      "measurements": [
        {
          "key": "temp",
          "name": "Temperature",
          "class": "analog_numeric",
          "data_type": "float",
          "unit": "celsius",
          "unit_symbol": "\u00b0C",
          "bounds": {
            "min": -50,
            "max": 80
          },
          "history": true,
          "history_suffix": "temp",
          "display": {
            "precision": 1,
            "chart": true
          }
        },
        {
          "key": "hum",
          "name": "Humidity",
          "class": "analog_numeric",
          "data_type": "float",
          "unit": "percent",
          "unit_symbol": "%",
          "bounds": {
            "min": 0,
            "max": 100
          },
          "history": true,
          "history_suffix": "hum",
          "display": {
            "precision": 1,
            "chart": true
          }
        }
      ]
    },
    {
      "id": "first_floor",
      "name": "First Floor",
      "category": "environmental",
      "adapter": "thermopro_ble",
      "measurements": [
        {
          "key": "temp",
          "name": "Temperature",
          "class": "analog_numeric",
          "data_type": "float",
          "unit": "celsius",
          "unit_symbol": "\u00b0C",
          "bounds": {
            "min": -50,
            "max": 80
          },
          "history": true,
          "history_suffix": "temp",
          "display": {
            "precision": 1,
            "chart": true
          }
        },
        {
          "key": "hum",
          "name": "Humidity",
          "class": "analog_numeric",
          "data_type": "float",
          "unit": "percent",
          "unit_symbol": "%",
          "bounds": {
            "min": 0,
            "max": 100
          },
          "history": true,
          "history_suffix": "hum",
          "display": {
            "precision": 1,
            "chart": true
          }
        }
      ]
    },
    {
      "id": "outside",
      "name": "Outside",
      "category": "environmental",
      "adapter": "thermopro_ble",
      "measurements": [
        {
          "key": "temp",
          "name": "Temperature",
          "class": "analog_numeric",
          "data_type": "float",
          "unit": "celsius",
          "unit_symbol": "\u00b0C",
          "bounds": {
            "min": -50,
            "max": 80
          },
          "history": true,
          "history_suffix": "temp",
          "display": {
            "precision": 1,
            "chart": true
          }
        },
        {
          "key": "hum",
          "name": "Humidity",
          "class": "analog_numeric",
          "data_type": "float",
          "unit": "percent",
          "unit_symbol": "%",
          "bounds": {
            "min": 0,
            "max": 100
          },
          "history": true,
          "history_suffix": "hum",
          "display": {
            "precision": 1,
            "chart": true
          }
        }
      ]
    }
  ]
}
)MANIFEST";
