#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

INPUT="${1:-dashboard/dashboard.html}"
OUTPUT="${2:-dashboard/dashboard.h}"

cat > "$OUTPUT" <<'EOF2'
#pragma once
// dashboard.h - embedded dashboard payload
// Auto-generated from dashboard/dashboard.html by scripts/generate-header.sh
// Do not edit this file directly - edit dashboard/dashboard.html instead.

#if defined(PROGMEM)
#define DASHBOARD_STORAGE_ATTR PROGMEM
#else
#define DASHBOARD_STORAGE_ATTR
#endif

static const char DASHBOARD_HTML[] DASHBOARD_STORAGE_ATTR = R"DASH64(
EOF2
cat "$INPUT" >> "$OUTPUT"
cat >> "$OUTPUT" <<'EOF2'
)DASH64";
EOF2

echo "Generated $OUTPUT from $INPUT"
