#!/usr/bin/env bash
# scripts/generate-header.sh
# Generate dashboard/dashboard.h from the dashboard HTML source.
#
# The HTML is gzip-compressed before embedding to reduce flash usage
# and HTTP transfer time (~190KB -> ~45KB). The firmware serves it with
# Content-Encoding: gzip so the browser decompresses transparently.
#
# Usage:
#   ./scripts/generate-header.sh [input] [output]
#
# Defaults:
#   input  = dashboard/dashboard.html  (or .min.html if it exists)
#   output = dashboard/dashboard.h
#
# If dashboard/dashboard.min.html exists it is used automatically,
# otherwise dashboard/dashboard.html is used. Pass an explicit input
# path to override this behaviour.
#
# The generated .h is committed to the repo — it is the embedded
# payload compiled into firmware.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

INPUT="${1:-dashboard/dashboard.html}"
OUTPUT="${2:-dashboard/dashboard.h}"

# Auto-upgrade to minified version if it exists and no explicit input given
if [[ $# -eq 0 ]]; then
  MINIFIED="${INPUT%.html}.min.html"
  if [[ -f "$MINIFIED" ]]; then
    INPUT="$MINIFIED"
    echo "Using minified source: $INPUT"
  fi
fi

if [[ ! -f "$INPUT" ]]; then
  echo "ERROR: Input file not found: $INPUT"
  exit 1
fi

# Extract dashboard version from source for the header comment
DASH_VERSION=$(grep -oP "App\.version\s*=\s*'[^']+'" "$INPUT" | head -1 || echo "unknown")

# Get raw size before compression
RAW_SIZE=$(wc -c < "$INPUT")

# Gzip compress the HTML
TMPGZ=$(mktemp /tmp/dashboard.gz.XXXXXX)
trap "rm -f '$TMPGZ'" EXIT
gzip -9 -c "$INPUT" > "$TMPGZ"
GZ_SIZE=$(wc -c < "$TMPGZ")

# Calculate compression ratio
SAVED=$((RAW_SIZE - GZ_SIZE))
PCT=$(( SAVED * 100 / RAW_SIZE ))

# Generate C header with gzip byte array
# Use python3 for binary->hex conversion (xxd not always available)
python3 - "$TMPGZ" "$OUTPUT" "$INPUT" "$DASH_VERSION" "$RAW_SIZE" "$GZ_SIZE" "$PCT" << 'PYEOF'
import sys

gz_path = sys.argv[1]
out_path = sys.argv[2]
src_name = sys.argv[3]
dash_ver = sys.argv[4]
raw_sz   = sys.argv[5]
gz_sz    = sys.argv[6]
pct      = sys.argv[7]

with open(gz_path, "rb") as f:
    data = f.read()

lines = []
lines.append("#pragma once")
lines.append(f"// dashboard.h - embedded dashboard payload (gzip compressed)")
lines.append(f"// Auto-generated from {src_name} by scripts/generate-header.sh")
lines.append(f"// Do not edit this file directly - edit dashboard/dashboard.html instead.")
lines.append(f"//")
lines.append(f"// Dashboard version: {dash_ver}")
lines.append(f"// Raw size: {raw_sz} bytes -> Gzip size: {gz_sz} bytes ({pct}% reduction)")
lines.append(f"//")
lines.append(f"// The firmware serves this with Content-Encoding: gzip.")
lines.append(f"// Browsers decompress transparently.")
lines.append(f"")
lines.append(f"#if defined(PROGMEM)")
lines.append(f"#define DASHBOARD_STORAGE_ATTR PROGMEM")
lines.append(f"#else")
lines.append(f"#define DASHBOARD_STORAGE_ATTR")
lines.append(f"#endif")
lines.append(f"")
lines.append(f"static const uint8_t DASHBOARD_HTML_GZ[] DASHBOARD_STORAGE_ATTR = {{")

# Format as hex bytes, 16 per line
for i in range(0, len(data), 16):
    chunk = data[i:i+16]
    hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
    if i + 16 < len(data):
        hex_vals += ","
    lines.append(f"  {hex_vals}")

lines.append(f"}};")
lines.append(f"")
lines.append(f"static const size_t DASHBOARD_HTML_GZ_LEN = sizeof(DASHBOARD_HTML_GZ);")
lines.append(f"")

with open(out_path, "w") as f:
    f.write("\n".join(lines) + "\n")
PYEOF

echo "Generated $OUTPUT from $INPUT"
echo "  Raw: ${RAW_SIZE} bytes -> Gzip: ${GZ_SIZE} bytes (saved ${SAVED} bytes, ${PCT}%)"
