#!/usr/bin/env bash
# generate-header-v7.3.4.2.sh - Regenerates dashboard-v7.3.4.2.h from dashboard-v7.3.4.2.html
set -euo pipefail
INPUT="${1:-dashboard-v7.3.4.2.html}"
OUTPUT="${2:-dashboard-v7.3.4.2.h}"
cat > "$OUTPUT" <<'EOF'
#pragma once
// dashboard-v7.3.4.2.h - embedded dashboard payload
// Auto-generated from dashboard-v7.3.4.2.html by generate-header-v7.3.4.2.sh
// Do not edit this file directly - edit dashboard-v7.3.4.2.html instead.

#if defined(PROGMEM)
  #define DASHBOARD_STORAGE_ATTR PROGMEM
#else
  #define DASHBOARD_STORAGE_ATTR
#endif

static const char DASHBOARD_HTML[] DASHBOARD_STORAGE_ATTR = R"DASH64(
EOF
cat "$INPUT" >> "$OUTPUT"
cat >> "$OUTPUT" <<'EOF'
)DASH64";
EOF
echo "Generated $OUTPUT from $INPUT"
