#!/usr/bin/env python3
from __future__ import annotations

import argparse
import difflib
import json
import re
import sys
from pathlib import Path
from typing import Dict, List

from sensor_manifest_lib import ManifestError, fixture_manifest, load_aggregator_config, load_manifest, manifest_v2

VERSION = "7.5.5.1"
ROOT = Path(__file__).resolve().parents[1]
GATEWAY_MANIFEST_H_PATH = ROOT / "src" / "gateway_manifest.h"
AGGREGATOR_CONFIG_H_PATH = ROOT / "src" / "aggregator_config.h"
AGGREGATOR_JSON_PATH = ROOT / "config" / "aggregator.json"
MANIFEST_PATH = ROOT / "config" / "sensors.json"
HEADER_PATH = ROOT / "dashboard" / "sensor_history_multi.h"
YAML_PATH = ROOT / "firmware" / "esp32-c3-multi-sensor.yaml"
JS_PATH = ROOT / "dashboard" / "dashboard.js"
FIXTURE_SENSORS_PATH = ROOT / "tests" / "fixtures" / "sensors.json"
FIXTURE_MANIFEST_PATH = ROOT / "tests" / "fixtures" / "manifest.json"
FIXTURE_STATUS_PATH = ROOT / "tests" / "fixtures" / "api-status.json"

HEADER_BEGIN = "// <<< SENSOR_MANIFEST:HEADER_BEGIN >>>"
HEADER_END = "// <<< SENSOR_MANIFEST:HEADER_END >>>"
JS_BEGIN = "// <<< SENSOR_MANIFEST:DEFAULT_SENSOR_META_BEGIN >>>"
JS_END = "// <<< SENSOR_MANIFEST:DEFAULT_SENSOR_META_END >>>"
YAML_AVG_BEGIN = " // <<< SENSOR_MANIFEST:AVERAGING_BEGIN >>>"
YAML_AVG_END = " // <<< SENSOR_MANIFEST:AVERAGING_END >>>"
YAML_GROUP_BEGIN = " # <<< SENSOR_MANIFEST:SORTING_GROUPS_BEGIN >>>"
YAML_GROUP_END = " # <<< SENSOR_MANIFEST:SORTING_GROUPS_END >>>"
YAML_THERMO_BEGIN = " # <<< SENSOR_MANIFEST:THERMOPRO_BEGIN >>>"
YAML_THERMO_END = " # <<< SENSOR_MANIFEST:THERMOPRO_END >>>"
YAML_RSSI_BEGIN = " # <<< SENSOR_MANIFEST:RSSI_BEGIN >>>"
YAML_RSSI_END = " # <<< SENSOR_MANIFEST:RSSI_END >>>"
YAML_TEXT_BEGIN = " # <<< SENSOR_MANIFEST:TEXT_SENSORS_BEGIN >>>"
YAML_TEXT_END = " # <<< SENSOR_MANIFEST:TEXT_SENSORS_END >>>"
YAML_PING_BOOT_BEGIN = " // <<< SENSOR_MANIFEST:PING_BOOT_BEGIN >>>"
YAML_PING_BOOT_END = " // <<< SENSOR_MANIFEST:PING_BOOT_END >>>"
ENTITY_BEGIN = "// <<< SENSOR_MANIFEST:ENTITY_BEGIN >>>"
ENTITY_END = "// <<< SENSOR_MANIFEST:ENTITY_END >>>"


class RenderError(Exception):
    pass


def replace_marker_block(text: str, begin: str, end: str, body: str) -> str:
    pattern = re.compile(re.escape(begin) + r".*?" + re.escape(end), flags=re.S)
    block = begin + "\n" + body.rstrip() + "\n" + end
    if not pattern.search(text):
        raise RenderError(f"Marker pair not found: {begin} .. {end}")
    return pattern.sub(lambda _m: block, text, count=1)



def unwrap_marker_body(block: str, begin: str, end: str) -> str:
    prefix = begin + '\n'
    suffix = '\n' + end
    if block.startswith(prefix) and block.endswith(suffix):
        return block[len(prefix):-len(suffix)]
    return block

def render_header_block(sensors: List[Dict[str, str]]) -> str:
    lines = [
        "// SensorSlot removed in v7.5.3.8 — all runtime state in SensorEntity devices[].",
        "// NUM_DEVICES = all logical devices in manifest.",
        "// NUM_SENSORS = persisted environmental sensor count only (backward-compat alias for SegmentSnapshot / HistoryMeta).",
    ]
    return "\n".join(lines)


def render_entity_block(sensors: List[Dict]) -> str:
    thermopro = [s for s in sensors if s.get("adapter", "thermopro_ble") == "thermopro_ble"]
    ping = [s for s in sensors if s.get("adapter") == "icmp_ping"]

    lines = [
        "// ── Generated SensorEntity arrays ──────────────────────────────────",
        "// Generated by render_sensor_config.py from config/sensors.json",
        "// Sole runtime model since v7.5.3.8 (SensorSlot removed)",
        "",
        "static const MetricDef metrics_thermopro[] = {",
        '  {"temp",  "Temperature", "\\xC2\\xB0""C", 0, true},',
        '  {"hum",   "Humidity",    "%",            0, true},',
        '  {"batt",  "Battery",     "%",            3, false},',
        '  {"rssi",  "RSSI",        "dBm",          3, false}',
        "};",
        "",
    ]

    if ping:
        lines.extend([
            "static const MetricDef metrics_ping[] = {",
            '  {"ping_ms",     "Latency", "ms", 0, true},',
            '  {"success_pct", "Success", "%",  0, true}',
            "};",
            "",
        ])

    for sensor in thermopro:
        sid = sensor["id"]
        lines.append(f"static HistoryBuffer entity_hbuf_{sid}_temp;")
        lines.append(f"static HistoryBuffer entity_hbuf_{sid}_hum;")

    for sensor in ping:
        sid = sensor["id"]
        lines.append(f"static HistoryBuffer entity_hbuf_{sid}_ping_ms;")
        lines.append(f"static HistoryBuffer entity_hbuf_{sid}_success_pct;")

    lines.extend([
        "",
        f"static constexpr int NUM_DEVICES = {len(sensors)};",
        f"static constexpr int NUM_ENV_SENSORS = {len(thermopro)};",
        "static constexpr int NUM_SENSORS = NUM_ENV_SENSORS;  // backward compat alias for persisted environmental history",
        "",
    ])

    # Emit PING_DEVICE_INDEX / PING_TARGET for the first icmp_ping device
    for i, s in enumerate(sensors):
        if s.get("adapter") == "icmp_ping":
            lines.extend([
                f"#define PING_DEVICE_INDEX {i}",
                f'#define PING_TARGET "{s["source"]["target"]}"',
                "",
            ])
            break

    lines.extend([
        "static SensorEntity devices[NUM_DEVICES] = {",
    ])

    for sensor in sensors:
        sid = sensor["id"]
        name = sensor["name"]
        adapter = sensor.get("adapter", "thermopro_ble")

        if adapter == "thermopro_ble":
            mac = sensor["mac"]
            lines.extend([
                "  {",
                f'    .id = "{sid}", .name = "{name}",',
                '    .category_id = 0, .adapter = "thermopro_ble",',
                "    .metric_defs = metrics_thermopro,",
                "    .metric_states = {",
                f"      {{.current_value = NAN, .accumulator = 0, .sample_count = 0, .valid = false, .last_update_epoch = 0, .history = &entity_hbuf_{sid}_temp}},",
                f"      {{.current_value = NAN, .accumulator = 0, .sample_count = 0, .valid = false, .last_update_epoch = 0, .history = &entity_hbuf_{sid}_hum}},",
                "      {.current_value = NAN, .accumulator = 0, .sample_count = 0, .valid = false, .last_update_epoch = 0, .history = nullptr},",
                "      {.current_value = NAN, .accumulator = 0, .sample_count = 0, .valid = false, .last_update_epoch = 0, .history = nullptr}",
                "    },",
                "    .metric_count = 4,",
                f'    .mac = "{mac}",',
                "    .last_rssi = 0, .last_seen_epoch = 0",
                "  },",
            ])
        elif adapter == "icmp_ping":
            lines.extend([
                "  {",
                f'    .id = "{sid}", .name = "{name}",',
                '    .category_id = 2, .adapter = "icmp_ping",',
                "    .metric_defs = metrics_ping,",
                "    .metric_states = {",
                f"      {{.current_value = NAN, .accumulator = 0, .sample_count = 0, .valid = false, .last_update_epoch = 0, .history = &entity_hbuf_{sid}_ping_ms}},",
                f"      {{.current_value = NAN, .accumulator = 0, .sample_count = 0, .valid = false, .last_update_epoch = 0, .history = &entity_hbuf_{sid}_success_pct}},",
                "      {.current_value = NAN, .accumulator = 0, .sample_count = 0, .valid = false, .last_update_epoch = 0, .history = nullptr},",
                "      {.current_value = NAN, .accumulator = 0, .sample_count = 0, .valid = false, .last_update_epoch = 0, .history = nullptr}",
                "    },",
                "    .metric_count = 2,",
                '    .mac = "",',
                "    .last_rssi = 0, .last_seen_epoch = 0",
                "  },",
            ])

    lines.append("};")
    return "\n".join(lines)


def render_js_block(sensors: List[Dict]) -> str:
    # DEFAULT_SENSOR_META only contains environmental (BLE) sensors
    env_sensors = [s for s in sensors if s.get("adapter", "thermopro_ble") == "thermopro_ble"]
    lines = ["var DEFAULT_SENSOR_META = ["]
    for sensor in env_sensors:
        lines.append(f"  {{ id: '{sensor['id']}', name: '{sensor['name']}' }},")
    lines.append("];\n")
    return "\n".join(lines)


def avg_lines(sensor: Dict, idx: int) -> List[str]:
    sid = sensor["id"]
    name = sensor["name"]
    return [
        f" // ── {name} ─────────────────────────────────────",
        f" devices[{idx}].compute_and_format(epoch);",
        f" id(avg_temp_{sid}).publish_state(devices[{idx}].temp_avg_str);",
        f" id(avg_hum_{sid}).publish_state(devices[{idx}].hum_avg_str);",
        f" if (devices[{idx}].batt_last >= 0) id(battery_{sid}).publish_state(devices[{idx}].batt_str);",
        "",
    ]


def render_yaml_averaging(sensors: List[Dict], all_sensors: List[Dict] = None) -> str:
    """Generate the interval averaging lambda.
    sensors     = ThermoPro-only list (existing behavior for compute_and_format calls).
    all_sensors = full device list; adds compute_averages() for non-ThermoPro history devices."""
    lines = [YAML_AVG_BEGIN]
    for idx, sensor in enumerate(sensors):
        lines.extend(avg_lines(sensor, idx))

    # Add compute_averages() for icmp_ping (and any future non-ThermoPro) devices
    if all_sensors:
        for i, s in enumerate(all_sensors):
            if s.get("adapter") == "icmp_ping":
                lines.extend([
                    f" // ── {s['name']} (network) ──────────────────────────────",
                    f" devices[{i}].compute_averages(epoch);",
                    "",
                ])

    while lines and lines[-1] == "":
        lines.pop()
    lines.append(YAML_AVG_END)
    return "\n".join(lines)


def render_yaml_sorting_groups(sensors: List[Dict[str, str]]) -> str:
    lines = [YAML_GROUP_BEGIN]
    for idx, sensor in enumerate(sensors, start=1):
        lines.extend(
            [
                f" - id: group_{sensor['id']}",
                f"   name: \"{sensor['name']}\"",
                f"   sorting_weight: {idx * 10}",
            ]
        )
    lines.append(YAML_GROUP_END)
    return "\n".join(lines)


def thermopro_block(sensor: Dict[str, str], idx: int) -> str:
    sid = sensor["id"]
    name = sensor["name"]
    mac = sensor["mac"]
    return f''' # ══════════════════════════════════════════════════════════════════
 # SENSOR {idx + 1}: {name.upper()} — MAC {mac}
 # ══════════════════════════════════════════════════════════════════
 - platform: thermopro_ble
   mac_address: "{mac}"
   temperature:
     id: raw_temp_{sid}
     name: "{name} Temp Raw"
     internal: true
     on_value:
       then:
         - lambda: |-
             devices[{idx}].add_sample(0, x);
             devices[{idx}].mark_seen(::time(nullptr));
             auto now = id(sntp_time).now();
             if (now.is_valid()) {{
               char seen_buf[20];
               snprintf(seen_buf, sizeof(seen_buf), "%02d:%02d:%02d %02d/%02d", now.hour, now.minute, now.second, now.month, now.day_of_month);
               id(last_seen_{sid}).publish_state(seen_buf);
             }}
             if (!isnan(x) && x > -50.0f && x < 80.0f) {{
               float f = x * 9.0f / 5.0f + 32.0f;
               char buf[32];
               snprintf(buf, sizeof(buf), "%.1f \\xC2\\xB0" "C / %.1f \\xC2\\xB0" "F", x, f);
               id(cur_temp_{sid}).publish_state(buf);
             }}
   humidity:
     id: raw_hum_{sid}
     name: "{name} Hum Raw"
     internal: true
     on_value:
       then:
         - lambda: |-
             devices[{idx}].add_sample(1, x);
             devices[{idx}].mark_seen(::time(nullptr));
             auto now = id(sntp_time).now();
             if (now.is_valid()) {{
               char seen_buf[20];
               snprintf(seen_buf, sizeof(seen_buf), "%02d:%02d:%02d %02d/%02d", now.hour, now.minute, now.second, now.month, now.day_of_month);
               id(last_seen_{sid}).publish_state(seen_buf);
             }}
             if (!isnan(x) && x >= 0.0f && x <= 100.0f) {{
               char buf[16];
               snprintf(buf, sizeof(buf), "%.1f %%", x);
               id(cur_hum_{sid}).publish_state(buf);
             }}
   battery_level:
     id: raw_batt_{sid}
     name: "{name} Battery Raw"
     internal: true
     on_value:
       then:
         - lambda: |-
             devices[{idx}].set_battery(x);
             devices[{idx}].mark_seen(::time(nullptr));
             auto now = id(sntp_time).now();
             if (now.is_valid()) {{
               char seen_buf[20];
               snprintf(seen_buf, sizeof(seen_buf), "%02d:%02d:%02d %02d/%02d", now.hour, now.minute, now.second, now.month, now.day_of_month);
               id(last_seen_{sid}).publish_state(seen_buf);
             }}
             if (devices[{idx}].batt_last >= 0) id(battery_{sid}).publish_state(devices[{idx}].batt_str);
'''


def render_yaml_thermopro(sensors: List[Dict[str, str]]) -> str:
    parts = [YAML_THERMO_BEGIN]
    for idx, sensor in enumerate(sensors):
        parts.append(thermopro_block(sensor, idx).rstrip())
        parts.append("")
    while parts and parts[-1] == "":
        parts.pop()
    parts.append(YAML_THERMO_END)
    return "\n".join(parts)


def rssi_block(sensor: Dict[str, str]) -> str:
    sid = sensor["id"]
    name = sensor["name"]
    mac = sensor["mac"]
    return f'''- platform: ble_rssi
  mac_address: "{mac}"
  name: "{name} RSSI"
  id: {sid}_rssi
  icon: "mdi:signal"
  filters:
    - exponential_moving_average:
        alpha: 0.3
        send_every: 3
        send_first_at: 1
  web_server:
    sorting_group_id: group_{sid}
    sorting_weight: 16'''


def render_yaml_rssi(sensors: List[Dict[str, str]]) -> str:
    parts = [YAML_RSSI_BEGIN]
    for sensor in sensors:
        parts.append(rssi_block(sensor))
        parts.append("")
    while parts and parts[-1] == "":
        parts.pop()
    parts.append(YAML_RSSI_END)
    return "\n".join(parts)


def text_sensor_block(sensor: Dict[str, str]) -> str:
    sid = sensor["id"]
    name = sensor["name"]
    return f'''# ══════════════════════════════════════════════════════════════════
# {name.upper()} — current readings + 15m averages + battery + last seen
# ══════════════════════════════════════════════════════════════════
- platform: template
  name: "{name} Temperature"
  id: cur_temp_{sid}
  icon: "mdi:thermometer"
  update_interval: never
  web_server:
    sorting_group_id: group_{sid}
    sorting_weight: 1
- platform: template
  name: "{name} Humidity"
  id: cur_hum_{sid}
  icon: "mdi:water-percent"
  update_interval: never
  web_server:
    sorting_group_id: group_{sid}
    sorting_weight: 2
- platform: template
  name: "{name} Temp (15m avg)"
  id: avg_temp_{sid}
  icon: "mdi:chart-line"
  update_interval: never
  web_server:
    sorting_group_id: group_{sid}
    sorting_weight: 3
- platform: template
  name: "{name} Humidity (15m avg)"
  id: avg_hum_{sid}
  icon: "mdi:chart-line"
  update_interval: never
  web_server:
    sorting_group_id: group_{sid}
    sorting_weight: 4
- platform: template
  name: "{name} Battery"
  id: battery_{sid}
  icon: "mdi:battery"
  update_interval: never
  web_server:
    sorting_group_id: group_{sid}
    sorting_weight: 5
- platform: template
  name: "{name} Last Seen"
  id: last_seen_{sid}
  icon: "mdi:clock-check-outline"
  update_interval: never
  web_server:
    sorting_group_id: group_{sid}
    sorting_weight: 6'''


def render_yaml_text_sensors(sensors: List[Dict[str, str]]) -> str:
    parts = [YAML_TEXT_BEGIN]
    for sensor in sensors:
        parts.append(text_sensor_block(sensor))
        parts.append("")
    while parts and parts[-1] == "":
        parts.pop()
    parts.append(YAML_TEXT_END)
    return "\n".join(parts)


def render_yaml_ping_boot(sensors: List[Dict]) -> str:
    """Generate the on_boot priority-600 lambda body for icmp_ping adapter initialization.
    The lambda is emitted only when an icmp_ping device is present; otherwise it is empty."""
    ping_devices = [s for s in sensors if s.get("adapter") == "icmp_ping"]
    lines = [YAML_PING_BOOT_BEGIN]
    if ping_devices:
        lines.extend([
            " #ifdef PING_DEVICE_INDEX",
            " static PingAdapter ping_adapter;",
            " ping_adapter.start(PING_DEVICE_INDEX, PING_TARGET);",
            " #endif",
        ])
    lines.append(YAML_PING_BOOT_END)
    return "\n".join(lines)


def render_header_file(path: Path, sensors: List[Dict[str, str]]) -> str:
    text = path.read_text(encoding="utf-8")
    text = re.sub(r"sensor_history_multi-v[0-9.]+\.h", f"sensor_history_multi-v{VERSION}.h", text)
    text = re.sub(
        r"// ── SENSOR COUNT CONFIGURATION GUIDE \(v[0-9.]+\) ──",
        f"// ── SENSOR COUNT CONFIGURATION GUIDE (v{VERSION}) ──",
        text,
    )
    text = replace_marker_block(text, HEADER_BEGIN, HEADER_END, render_header_block(sensors))
    text = replace_marker_block(text, ENTITY_BEGIN, ENTITY_END, render_entity_block(sensors))
    return text


def render_js_file(path: Path, sensors: List[Dict[str, str]]) -> str:
    text = path.read_text(encoding="utf-8")
    text = re.sub(r"App\.version = 'v[0-9.]+'", f"App.version = 'v{VERSION}'", text)
    return replace_marker_block(text, JS_BEGIN, JS_END, render_js_block(sensors))



def apply_yaml_marker_block(text: str, begin: str, end: str, body: str) -> str:
    begin_core = begin.lstrip()
    end_core = end.lstrip()

    marker_match = re.search(
        rf'^(?P<indent>[ \t]*){re.escape(begin_core)}[ \t]*$',
        text,
        flags=re.M,
    )
    if not marker_match:
        raise RenderError(f'YAML marker pair not found: {begin} .. {end}')

    indent = marker_match.group("indent")

    body_lines = body.rstrip().splitlines()
    nonblank = [line for line in body_lines if line.strip()]
    if nonblank:
        min_indent = min(len(re.match(r'[ \t]*', line).group(0)) for line in nonblank)
        body_lines = [line[min_indent:] if line.strip() else '' for line in body_lines]

    indented_body = "\n".join((indent + line) if line.strip() else '' for line in body_lines)
    block = indent + begin_core + "\n" + indented_body.rstrip() + "\n" + indent + end_core

    pattern = re.compile(
        rf'^[ \t]*{re.escape(begin_core)}[ \t]*$.*?^[ \t]*{re.escape(end_core)}[ \t]*$',
        flags=re.M | re.S,
    )
    if not pattern.search(text):
        raise RenderError(f'YAML marker block not found: {begin} .. {end}')
    return pattern.sub(lambda _m: block, text, count=1)

def render_yaml_file(path: Path, sensors: List[Dict]) -> str:
    # YAML blocks only cover ThermoPro BLE sensors; filter other adapters
    ble_sensors = [s for s in sensors if s.get("adapter", "thermopro_ble") == "thermopro_ble"]
    text = path.read_text(encoding="utf-8")
    text = re.sub(r"# ESP32-C3 Multi-Sensor Gateway - v[0-9.]+", f"# ESP32-C3 Multi-Sensor Gateway - v{VERSION}", text)
    text = re.sub(r'register_history_handler\((.*?), "v[0-9.]+"\);', rf'register_history_handler(\1, "v{VERSION}");', text, count=1)
    text = text.replace("v7.4.5.1", f"v{VERSION}")
    text = apply_yaml_marker_block(text, YAML_AVG_BEGIN, YAML_AVG_END, unwrap_marker_body(render_yaml_averaging(ble_sensors, all_sensors=sensors), YAML_AVG_BEGIN, YAML_AVG_END))
    text = apply_yaml_marker_block(text, YAML_GROUP_BEGIN, YAML_GROUP_END, unwrap_marker_body(render_yaml_sorting_groups(ble_sensors), YAML_GROUP_BEGIN, YAML_GROUP_END))
    text = apply_yaml_marker_block(text, YAML_THERMO_BEGIN, YAML_THERMO_END, unwrap_marker_body(render_yaml_thermopro(ble_sensors), YAML_THERMO_BEGIN, YAML_THERMO_END))
    text = apply_yaml_marker_block(text, YAML_RSSI_BEGIN, YAML_RSSI_END, unwrap_marker_body(render_yaml_rssi(ble_sensors), YAML_RSSI_BEGIN, YAML_RSSI_END))
    text = apply_yaml_marker_block(text, YAML_TEXT_BEGIN, YAML_TEXT_END, unwrap_marker_body(render_yaml_text_sensors(ble_sensors), YAML_TEXT_BEGIN, YAML_TEXT_END))
    text = apply_yaml_marker_block(text, YAML_PING_BOOT_BEGIN, YAML_PING_BOOT_END, unwrap_marker_body(render_yaml_ping_boot(sensors), YAML_PING_BOOT_BEGIN, YAML_PING_BOOT_END))
    return text


def unified_diff(old: str, new: str, label: str) -> str:
    return "".join(
        difflib.unified_diff(
            old.splitlines(keepends=True),
            new.splitlines(keepends=True),
            fromfile=f"{label} (current)",
            tofile=f"{label} (expected)",
        )
    )


def write_if_changed(path: Path, content: str) -> bool:
    old = path.read_text(encoding="utf-8") if path.exists() else None
    if old == content:
        return False
    path.write_text(content, encoding="utf-8")
    return True


def generate_gateway_manifest_h(sensors: List[Dict[str, str]], version: str) -> str:
    """Generate gateway_manifest.h with v2 manifest as C raw string literal."""
    manifest = manifest_v2(sensors, f"v{version}")
    manifest_json = json.dumps(manifest, indent=2, ensure_ascii=False)
    return f'''#pragma once
// gateway_manifest.h — Auto-generated v2 manifest JSON
// Generated by scripts/render_sensor_config.py from config/sensors.json
// DO NOT EDIT — regenerate via: python3 scripts/render_sensor_config.py --write

static const char GATEWAY_MANIFEST_JSON[] = R"MANIFEST(
{manifest_json}
)MANIFEST";
'''


def generate_aggregator_config_h(aggregator_config: Dict | None) -> str:
    """Generate src/aggregator_config.h from config/aggregator.json (or disabled stub)."""
    if aggregator_config is None:
        return (
            "#pragma once\n"
            "// Generated by render_sensor_config.py — no aggregator.json present\n"
            "#define AGGREGATOR_ENABLED 0\n"
        )

    satellites = aggregator_config.get("satellites", [])
    n = len(satellites)

    ids_literal = ", ".join(f'"{s["id"]}"' for s in satellites)
    names_literal = ", ".join(f'"{s["name"]}"' for s in satellites)
    urls_literal = ", ".join(f'"{s["base_url"].rstrip("/")}"' for s in satellites)
    polls_literal = ", ".join(str(s.get("poll_interval_seconds", 30)) for s in satellites)

    return (
        "#pragma once\n"
        "// Generated by render_sensor_config.py — do not edit manually\n"
        f"#define AGGREGATOR_ENABLED 1\n"
        f"#define MAX_SATELLITES {n}\n"
        "#define AGGREGATOR_POLL_INTERVAL_DEFAULT 30\n"
        "\n"
        f"static const char* SATELLITE_IDS[] = {{{ids_literal}}};\n"
        f"static const char* SATELLITE_NAMES[] = {{{names_literal}}};\n"
        f"static const char* SATELLITE_URLS[] = {{{urls_literal}}};\n"
        f"static const int SATELLITE_POLL_INTERVALS[] = {{{polls_literal}}};\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Render generated sensor-config sections from config/sensors.json")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--check", action="store_true", help="Verify generated files are in sync")
    group.add_argument("--write", action="store_true", help="Rewrite generated files in place")
    args = parser.parse_args()

    try:
        sensors = load_manifest(MANIFEST_PATH)
    except ManifestError as exc:
        print(f"Manifest error: {exc}", file=sys.stderr)
        return 2

    try:
        aggregator_config = load_aggregator_config(AGGREGATOR_JSON_PATH)
    except ManifestError as exc:
        print(f"Aggregator config error: {exc}", file=sys.stderr)
        return 2

    expected_header = render_header_file(HEADER_PATH, sensors)
    expected_yaml = render_yaml_file(YAML_PATH, sensors)
    expected_js = render_js_file(JS_PATH, sensors)
    expected_fixture_sensors = json.dumps(fixture_manifest(sensors), indent=2) + "\n"
    expected_fixture_manifest = json.dumps(manifest_v2(sensors, f"v{VERSION}"), indent=2, ensure_ascii=False) + "\n"
    expected_fixture_status = json.dumps(
        {
            "ok": True,
            "version": f"v{VERSION}",
            "sensor_count": len(sensors),
            "sensors": fixture_manifest(sensors),
            "mode": "active-manifest",
            "connected": True,
        },
        indent=2,
    ) + "\n"
    expected_gateway_manifest_h = generate_gateway_manifest_h(sensors, VERSION)
    expected_aggregator_config_h = generate_aggregator_config_h(aggregator_config)

    expected = {
        HEADER_PATH: expected_header,
        YAML_PATH: expected_yaml,
        JS_PATH: expected_js,
        FIXTURE_SENSORS_PATH: expected_fixture_sensors,
        FIXTURE_MANIFEST_PATH: expected_fixture_manifest,
        FIXTURE_STATUS_PATH: expected_fixture_status,
        GATEWAY_MANIFEST_H_PATH: expected_gateway_manifest_h,
        AGGREGATOR_CONFIG_H_PATH: expected_aggregator_config_h,
    }

    if args.check:
        diffs: List[str] = []
        for path, content in expected.items():
            current = path.read_text(encoding="utf-8") if path.exists() else ""
            if current != content:
                diffs.append(unified_diff(current, content, str(path.relative_to(ROOT))))
        if diffs:
            sys.stderr.write("Generated files are out of sync with config/sensors.json.\n")
            sys.stderr.write("Run: python3 scripts/render_sensor_config.py --write\n\n")
            sys.stderr.write("\n".join(diffs))
            return 1
        print("render_sensor_config: PASS")
        return 0

    changed = []
    for path, content in expected.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        if write_if_changed(path, content):
            changed.append(str(path.relative_to(ROOT)))
    if changed:
        print("Updated generated files:")
        for item in changed:
            print(f" - {item}")
    else:
        print("No generated-file changes were needed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
