#pragma once
// Generated by render_sensor_config.py — do not edit manually
#define AGGREGATOR_ENABLED 1
#define MAX_SATELLITES 1
#define AGGREGATOR_POLL_INTERVAL_DEFAULT 30

static const char* SATELLITE_IDS[] = {"gw-main"};
static const char* SATELLITE_NAMES[] = {"Main Gateway (C3)"};
static const char* SATELLITE_URLS[] = {"http://192.168.120.189"};
static const int SATELLITE_POLL_INTERVALS[] = {30};
