#pragma once
// Generated by render_sensor_config.py — do not edit manually
#define AGGREGATOR_ENABLED 1
#define MAX_SATELLITES 2
#define AGGREGATOR_POLL_INTERVAL_DEFAULT 30

static const char* SATELLITE_IDS[] = {"gw-main", "gw-garage"};
static const char* SATELLITE_NAMES[] = {"Main Gateway", "Garage Sensors"};
static const char* SATELLITE_URLS[] = {"http://192.168.120.189", "http://192.168.10.21"};
static const int SATELLITE_POLL_INTERVALS[] = {30, 30};
