#pragma once
// Generated by render_sensor_config.py — do not edit manually
#define AGGREGATOR_ENABLED 1
#define MAX_SATELLITES 2
#define AGG_MANIFEST_BUF_SIZE 8192
#define AGGREGATOR_POLL_INTERVAL_DEFAULT 30

static const char* SATELLITE_IDS[] = {"sat-c3-4m-189", "sat-esp32-4m-190"};
static const char* SATELLITE_NAMES[] = {"First satellite - c3 supermini 4mb flash", "Second satellite - esp32 wroom 4mb flash"};
static const char* SATELLITE_URLS[] = {"http://192.168.120.189", "http://192.168.120.190"};
static const int SATELLITE_POLL_INTERVALS[] = {30, 30};
