#pragma once
// gateway_manifest.h — generated v2 manifest JSON
// Auto-generated by scripts/render_sensor_config.py — do not edit

static const char GATEWAY_MANIFEST_JSON[] = R"MANIFEST(
{
  "ok": true,
  "schema_version": 2,
  "source": "active-manifest",
  "version": "v7.5.0.1",
  "sensor_count": 3,
  "metrics": [
    {
      "key": "temp",
      "name": "Temperature",
      "unit": "celsius",
      "unit_symbol": "°C",
      "bounds": {
        "min": -50,
        "max": 80
      },
      "history_suffix": "temp"
    },
    {
      "key": "hum",
      "name": "Humidity",
      "unit": "percent",
      "unit_symbol": "%",
      "bounds": {
        "min": 0,
        "max": 100
      },
      "history_suffix": "hum"
    }
  ],
  "sensors": [
    {
      "id": "office",
      "name": "Office",
      "metrics": [
        {
          "key": "temp",
          "history": "/history/office/temp"
        },
        {
          "key": "hum",
          "history": "/history/office/hum"
        }
      ]
    },
    {
      "id": "first_floor",
      "name": "First Floor",
      "metrics": [
        {
          "key": "temp",
          "history": "/history/first_floor/temp"
        },
        {
          "key": "hum",
          "history": "/history/first_floor/hum"
        }
      ]
    },
    {
      "id": "outside",
      "name": "Outside",
      "metrics": [
        {
          "key": "temp",
          "history": "/history/outside/temp"
        },
        {
          "key": "hum",
          "history": "/history/outside/hum"
        }
      ]
    }
  ]
}
)MANIFEST";
