#pragma once
// gateway_manifest.h — Auto-generated v2 manifest JSON
// Generated by scripts/render_sensor_config.py from config/sensors.json
// DO NOT EDIT — regenerate via: python3 scripts/render_sensor_config.py --write

static const char GATEWAY_MANIFEST_JSON[] = R"MANIFEST(
{
  "ok": true,
  "schema_version": 2,
  "source": "active-manifest",
  "version": "v7.5.5.1",
  "gateway": {
    "id": "gw-main",
    "name": "Main Gateway",
    "role": "satellite",
    "hardware": "ESP32-C3",
    "firmware_version": "v7.5.5.1",
    "api_version": "v2"
  },
  "history": {
    "backend": "nvs",
    "retention_hours": 1080,
    "ram_window_hours": 24,
    "sample_interval_seconds": 900
  },
  "sensor_count": 4,
  "metrics": [
    {
      "key": "temp",
      "name": "Temperature",
      "unit": "celsius",
      "unit_symbol": "°C",
      "class": "analog_numeric",
      "data_type": "float",
      "bounds": {
        "min": -50,
        "max": 80
      },
      "history": true,
      "history_suffix": "temp",
      "display": {
        "precision": 1,
        "chart": true
      }
    },
    {
      "key": "hum",
      "name": "Humidity",
      "unit": "percent",
      "unit_symbol": "%",
      "class": "analog_numeric",
      "data_type": "float",
      "bounds": {
        "min": 0,
        "max": 100
      },
      "history": true,
      "history_suffix": "hum",
      "display": {
        "precision": 1,
        "chart": true
      }
    }
  ],
  "sensors": [
    {
      "id": "office",
      "name": "Office",
      "category": "environmental",
      "adapter": "thermopro_ble",
      "source": {
        "mac": "DB:06:2C:58:8A:59"
      },
      "measurements": [
        {
          "key": "temp",
          "history_url": "/history/office/temp"
        },
        {
          "key": "hum",
          "history_url": "/history/office/hum"
        }
      ]
    },
    {
      "id": "first_floor",
      "name": "First Floor",
      "category": "environmental",
      "adapter": "thermopro_ble",
      "source": {
        "mac": "D5:D8:4C:25:06:49"
      },
      "measurements": [
        {
          "key": "temp",
          "history_url": "/history/first_floor/temp"
        },
        {
          "key": "hum",
          "history_url": "/history/first_floor/hum"
        }
      ]
    },
    {
      "id": "outside",
      "name": "Outside",
      "category": "environmental",
      "adapter": "thermopro_ble",
      "source": {
        "mac": "DF:EB:DE:19:11:6C"
      },
      "measurements": [
        {
          "key": "temp",
          "history_url": "/history/outside/temp"
        },
        {
          "key": "hum",
          "history_url": "/history/outside/hum"
        }
      ]
    },
    {
      "id": "wan_ping",
      "name": "WAN Latency",
      "category": "network",
      "adapter": "icmp_ping",
      "source": {
        "target": "8.8.8.8"
      },
      "measurements": [
        {
          "key": "ping_ms",
          "history_url": "/api/v2/history/wan_ping/ping_ms"
        },
        {
          "key": "success_pct",
          "history_url": "/api/v2/history/wan_ping/success_pct"
        }
      ]
    }
  ]
}
)MANIFEST";
